name: Helm Deployment

on:
  push:
    paths:
      - 'helm/**'

jobs:
  start:
    runs-on: ubuntu-latest
    steps:
      - name: Starting Workflow
        run: echo "Starting workflow for Helm deployment."

  deploy-helm-chart:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.TF_VAR_AWS_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.TF_VAR_AWS_SECRET_KEY }}
      AWS_REGION: "us-west-2"  # Adjust to your cluster's region

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli

      - name: Configure AWS CLI
        run: |
          aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
          aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
          aws configure set region $AWS_REGION

      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/

      - name: Update kubeconfig for EKS cluster
        run: |
          aws eks update-kubeconfig --name dev-cluster --region $AWS_REGION

      - name: Install Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

      - name: Deploy Helm Chart
        working-directory: ./helm/charts/tjh-backend
        run: |
          helm install tjh-backend . -f ./values.yaml --create-namespace --namespace tjh-backend
